spring.application.name=order-service

spring.datasource.url=jdbc:postgresql://localhost:5432/order
spring.datasource.username=microservice
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
server.port=8082

#Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.security.user.name=eureka
spring.security.user.password=password

spring.kafka.bootstrap-servers=localhost:9092



spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Actuator, Prometheus Endpoints
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health, prometheus
management.tracing.sampling.probability=1.0





